# Generated by Django 6.0.2 on 2026-02-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='project_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
