# Generated by Django 6.0.2 on 2026-02-24 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_graduate_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='project_link',
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='project_title',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField(blank=True, null=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.graduate')),
            ],
        ),
    ]
