# Generated by Django 6.0.2 on 2026-02-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graduate',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
    ]
