# Generated by Django 6.0.2 on 2026-02-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_graduate_linkedin_graduate_telegram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
